# Generated by Django 4.1.2 on 2022-10-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_song_lyric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.CharField(max_length=400),
        ),
    ]
