# Generated by Django 4.1.2 on 2022-11-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_lyric_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
