# Generated by Django 4.1.2 on 2022-11-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_remove_song_id_alter_song_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='id',
            field=models.IntegerField(default=int, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
